const TESTS_DATA = {
  test1: {
    title: "Test 1 – Base de Conocimiento",
    questions: [
      {id:1, tema:"Redes", enunciado:"En el modelo OSI, la capa responsable del control de congestión y enrutamiento es:", opciones:{A:"Transporte",B:"Enlace",C:"Red",D:"Sesión"}, correcta:"C", explicacion:""},
      {id:2, tema:"Redes", enunciado:"¿Cuál fue la principal razón por la que TCP/IP ganó frente a OSI?", opciones:{A:"Era más teórico",B:"Era más complejo",C:"Era práctico y ya estaba implementado",D:"Era más seguro"}, correcta:"C", explicacion:""},
      {id:3, tema:"Redes", enunciado:"IEEE 802.3 define:", opciones:{A:"Wi-Fi",B:"Ethernet",C:"Bluetooth",D:"WiMAX"}, correcta:"B", explicacion:""},
      {id:4, tema:"Redes", enunciado:"La dirección MAC opera en la capa:", opciones:{A:"Aplicación",B:"Transporte",C:"Enlace de datos",D:"Red"}, correcta:"C", explicacion:""},
      {id:5, tema:"Redes", enunciado:"En IPv4, el datagrama incluye:", opciones:{A:"Solo dirección MAC",B:"Cabecera y datos",C:"Solo payload",D:"Certificados digitales"}, correcta:"B", explicacion:""},
      {id:6, tema:"Redes", enunciado:"La codificación Manchester se caracteriza por:", opciones:{A:"Ausencia de transición",B:"Transición en cada bit",C:"Solo valores positivos",D:"Paridad integrada"}, correcta:"B", explicacion:""},
      {id:7, tema:"Redes", enunciado:"NRZ-I representa el bit 1 mediante:", opciones:{A:"Nivel bajo constante",B:"Transición de señal",C:"Ausencia de señal",D:"Frecuencia alta"}, correcta:"B", explicacion:""},
      {id:8, tema:"Redes", enunciado:"Una red clasificada como WAN se caracteriza por:", opciones:{A:"Alcance local",B:"Conexión personal",C:"Gran escala geográfica",D:"Red dentro de campus"}, correcta:"C", explicacion:""},
      {id:9, tema:"Redes", enunciado:"IEEE 802.11 corresponde a:", opciones:{A:"Ethernet",B:"Wi-Fi",C:"Token Ring",D:"ARPANET"}, correcta:"B", explicacion:""},
      {id:10, tema:"Redes", enunciado:"En el modelo OSI, la compresión y cifrado pertenecen a la capa:", opciones:{A:"Aplicación",B:"Presentación",C:"Transporte",D:"Física"}, correcta:"B", explicacion:""},
      {id:11, tema:"Seguridad", enunciado:"Un ataque que intercepta comunicación entre dos partes es:", opciones:{A:"XSS",B:"MITM",C:"DDoS",D:"Rootkit"}, correcta:"B", explicacion:""},
      {id:12, tema:"Seguridad", enunciado:"El phishing se basa principalmente en:", opciones:{A:"Fuerza bruta",B:"Ingeniería social",C:"Exploit kernel",D:"Cifrado débil"}, correcta:"B", explicacion:""},
      {id:13, tema:"Seguridad", enunciado:"Un ataque 0-Day explota:", opciones:{A:"Vulnerabilidades ya parcheadas",B:"Fallos no conocidos o no parcheados",C:"Errores físicos",D:"DNS mal configurado"}, correcta:"B", explicacion:""},
      {id:14, tema:"Seguridad", enunciado:"La confidencialidad garantiza:", opciones:{A:"Acceso libre",B:"No alteración",C:"No acceso no autorizado",D:"No pérdida eléctrica"}, correcta:"C", explicacion:""},
      {id:15, tema:"Seguridad", enunciado:"Un SIEM se utiliza para:", opciones:{A:"Cifrar discos",B:"Monitorizar y correlacionar eventos",C:"Crear usuarios",D:"Hacer RAID"}, correcta:"B", explicacion:""},
      {id:16, tema:"Seguridad", enunciado:"Un ataque DDoS busca:", opciones:{A:"Robar contraseñas",B:"Saturar recursos",C:"Modificar DNS",D:"Cifrar archivos"}, correcta:"B", explicacion:""},
      {id:17, tema:"Seguridad", enunciado:"Un rootkit tiene como objetivo:", opciones:{A:"Instalar antivirus",B:"Ocultar presencia maliciosa",C:"Configurar firewall",D:"Mejorar rendimiento"}, correcta:"B", explicacion:""},
      {id:18, tema:"Seguridad", enunciado:"El análisis forense incluye:", opciones:{A:"Eliminación de logs",B:"Preservación de evidencia",C:"Instalación de malware",D:"Cambio de BIOS"}, correcta:"B", explicacion:""},
      {id:19, tema:"Seguridad", enunciado:"RBAC significa:", opciones:{A:"Root Based Access Control",B:"Role-Based Access Control",C:"Remote Backup Active Control",D:"Random Binary Access Check"}, correcta:"B", explicacion:""},
      {id:20, tema:"Seguridad", enunciado:"La integridad se pierde cuando:", opciones:{A:"Se modifica información",B:"Se cifra correctamente",C:"Se autentica con MFA",D:"Se usa VPN"}, correcta:"A", explicacion:""},
      {id:21, tema:"SOR", enunciado:"Un Controlador de Dominio almacena:", opciones:{A:"Solo DNS",B:"Copia de la base AD",C:"Solo DHCP",D:"Solo usuarios locales"}, correcta:"B", explicacion:""},
      {id:22, tema:"SOR", enunciado:"Para promover un servidor a DC es necesario instalar:", opciones:{A:"IIS",B:"AD DS",C:"FTP",D:"RAID"}, correcta:"B", explicacion:""},
      {id:23, tema:"SOR", enunciado:"Un bosque puede contener:", opciones:{A:"Un solo dominio",B:"Varios dominios",C:"Solo RODC",D:"Solo OU"}, correcta:"B", explicacion:""},
      {id:24, tema:"SOR", enunciado:"Una OU permite:", opciones:{A:"Crear bosques",B:"Agrupar objetos y aplicar GPO",C:"Eliminar dominio",D:"Sustituir DC"}, correcta:"B", explicacion:""},
      {id:25, tema:"SOR", enunciado:"RSAT permite:", opciones:{A:"Instalar imágenes PXE",B:"Administrar roles desde cliente Windows",C:"Configurar BIOS",D:"Hacer RAID"}, correcta:"B", explicacion:""},
      {id:26, tema:"SOR", enunciado:"WDS permite:", opciones:{A:"Instalación remota por PXE",B:"Configurar RAID",C:"Crear OU",D:"Instalar antivirus"}, correcta:"A", explicacion:""},
      {id:27, tema:"SOR", enunciado:"Para unir un PC al dominio se requiere:", opciones:{A:"DNS funcional",B:"Bluetooth",C:"USB booteable",D:"Solo IP pública"}, correcta:"A", explicacion:""},
      {id:28, tema:"SOR", enunciado:"RAID5 utiliza:", opciones:{A:"Espejo",B:"Paridad distribuida",C:"Solo copia simple",D:"Cifrado AES"}, correcta:"B", explicacion:""},
      {id:29, tema:"SOR", enunciado:"En PowerShell, los cmdlets suelen comenzar por:", opciones:{A:"Exec-",B:"Get-/Set-/New-",C:"Run-",D:"Addonly-"}, correcta:"B", explicacion:""},
      {id:30, tema:"SOR", enunciado:"New-ADGroup crea:", opciones:{A:"OU",B:"Usuario",C:"Grupo",D:"Dominio"}, correcta:"C", explicacion:""},
      {id:31, tema:"SOR", enunciado:"Enable-PSRemoting permite:", opciones:{A:"Habilitar DHCP",B:"Permitir administración remota PowerShell",C:"Instalar RSAT",D:"Configurar RAID"}, correcta:"B", explicacion:""},
      {id:32, tema:"SOR", enunciado:"Un RODC es:", opciones:{A:"Editable",B:"Solo lectura",C:"DNS secundario",D:"Servidor DHCP"}, correcta:"B", explicacion:""},
      {id:33, tema:"SOR", enunciado:"El nivel funcional del dominio define:", opciones:{A:"Tamaño del disco",B:"Características habilitadas",C:"Número de usuarios",D:"Tipo de RAID"}, correcta:"B", explicacion:""},
      {id:34, tema:"SOR", enunciado:"ReFS es:", opciones:{A:"Protocolo red",B:"Sistema de archivos",C:"Servicio dominio",D:"Herramienta RSAT"}, correcta:"B", explicacion:""},
      {id:35, tema:"SOR", enunciado:"En LDAP, CN significa:", opciones:{A:"Control Node",B:"Common Name",C:"Central Network",D:"Core Name"}, correcta:"B", explicacion:""},
      {id:36, tema:"SOR", enunciado:"La autenticación en dominio es:", opciones:{A:"Local",B:"Centralizada",C:"Manual",D:"Peer-to-peer"}, correcta:"B", explicacion:""},
      {id:37, tema:"SOR", enunciado:"Un dominio representa:", opciones:{A:"Red física",B:"Límite de seguridad",C:"Router",D:"VLAN"}, correcta:"B", explicacion:""},
      {id:38, tema:"SOR", enunciado:"DHCP en dominio debe:", opciones:{A:"Estar autorizado en AD",B:"Ser local",C:"Estar desactivado",D:"Ser manual"}, correcta:"A", explicacion:""},
      {id:39, tema:"SOR", enunciado:"La replicación AD garantiza:", opciones:{A:"Igual IP",B:"Igual base en DCs",C:"Igual BIOS",D:"Igual RAM"}, correcta:"B", explicacion:""},
      {id:40, tema:"SOR", enunciado:"La instalación remota requiere:", opciones:{A:"PXE habilitado",B:"Solo USB",C:"Bluetooth",D:"Solo ISO local"}, correcta:"A", explicacion:""}
    ]
  },
  test2: {
    title: "Test 2 – Nivel Avanzado",
    questions: [
      {id:1, tema:"Redes", enunciado:"Un paquete viaja desde un cliente a un servidor web. ¿En qué capa OSI se realiza el enrutamiento?", opciones:{A:"Enlace",B:"Red",C:"Transporte",D:"Aplicación"}, correcta:"B", explicacion:""},
      {id:2, tema:"Redes", enunciado:"Si un switch trabaja con direcciones MAC, opera en la capa:", opciones:{A:"Física",B:"Enlace",C:"Red",D:"Transporte"}, correcta:"B", explicacion:""},
      {id:3, tema:"Redes", enunciado:"Una red MAN se caracteriza por:", opciones:{A:"Conectar dispositivos personales",B:"Conectar edificios dentro de una ciudad",C:"Conectar solo una casa",D:"Conectar solo un campus"}, correcta:"B", explicacion:""},
      {id:4, tema:"Redes", enunciado:"En el modelo TCP/IP, la capa “Internet” equivale aproximadamente a la capa OSI:", opciones:{A:"Transporte",B:"Aplicación",C:"Red",D:"Física"}, correcta:"C", explicacion:""},
      {id:5, tema:"Redes", enunciado:"La función “Keep Link Without Error” pertenece a:", opciones:{A:"Capa Física",B:"Capa Enlace",C:"Capa Red",D:"Capa Transporte"}, correcta:"B", explicacion:""},
      {id:6, tema:"Redes", enunciado:"Si un cable Ethernet está mal crimpado, el fallo afecta principalmente a:", opciones:{A:"Capa Aplicación",B:"Capa Transporte",C:"Capa Física",D:"Capa Sesión"}, correcta:"C", explicacion:""},
      {id:7, tema:"Redes", enunciado:"En Manchester diferencial, la sincronización se garantiza porque:", opciones:{A:"No hay transiciones",B:"Hay transición en cada periodo",C:"Usa paridad",D:"Usa compresión"}, correcta:"B", explicacion:""},
      {id:8, tema:"Redes", enunciado:"Una topología en estrella depende críticamente de:", opciones:{A:"Cable coaxial",B:"Nodo central",C:"Token Bus",D:"Router externo"}, correcta:"B", explicacion:""},
      {id:9, tema:"Redes", enunciado:"IEEE 802.15 está asociado a:", opciones:{A:"WiMAX",B:"Ethernet",C:"Bluetooth",D:"ARP"}, correcta:"C", explicacion:""},
      {id:10, tema:"Redes", enunciado:"Un datagrama IPv4 contiene información de:", opciones:{A:"Dirección origen y destino",B:"Dirección MAC física",C:"Solo puerto",D:"Certificados TLS"}, correcta:"A", explicacion:""},
      {id:11, tema:"Seguridad", enunciado:"Una empresa sufre saturación del servidor por múltiples equipos externos. Es un caso de:", opciones:{A:"MITM",B:"DDoS",C:"XSS",D:"Rootkit"}, correcta:"B", explicacion:""},
      {id:12, tema:"Seguridad", enunciado:"Un empleado recibe un correo falso del “director” pidiendo credenciales. Es:", opciones:{A:"Fuerza bruta",B:"Spear Phishing",C:"SQL Injection",D:"Botnet"}, correcta:"B", explicacion:""},
      {id:13, tema:"Seguridad", enunciado:"Un atacante intercepta tráfico para modificar datos antes de que lleguen al servidor. Es:", opciones:{A:"MITM",B:"Worm",C:"Ransomware",D:"ARP legítimo"}, correcta:"A", explicacion:""},
      {id:14, tema:"Seguridad", enunciado:"Un SIEM ayuda a:", opciones:{A:"Instalar antivirus",B:"Correlacionar eventos y detectar anomalías",C:"Crear RAID",D:"Configurar DHCP"}, correcta:"B", explicacion:""},
      {id:15, tema:"Seguridad", enunciado:"La autenticación multifactor combina:", opciones:{A:"Usuario + contraseña",B:"Algo que sabes + algo que tienes o eres",C:"Dos contraseñas",D:"DNS + DHCP"}, correcta:"B", explicacion:""},
      {id:16, tema:"Seguridad", enunciado:"Un keylogger tiene como objetivo:", opciones:{A:"Cifrar datos",B:"Capturar pulsaciones de teclado",C:"Generar paridad RAID",D:"Configurar firewall"}, correcta:"B", explicacion:""},
      {id:17, tema:"Seguridad", enunciado:"La integridad se protege mediante:", opciones:{A:"Hash",B:"IP pública",C:"Topología estrella",D:"PXE"}, correcta:"A", explicacion:""},
      {id:18, tema:"Seguridad", enunciado:"Un ataque Zero-Day es especialmente peligroso porque:", opciones:{A:"Ya existe parche",B:"No existe solución aún",C:"Solo afecta Linux",D:"Solo afecta DNS"}, correcta:"B", explicacion:""},
      {id:19, tema:"Seguridad", enunciado:"RBAC mejora seguridad porque:", opciones:{A:"Permite acceso total",B:"Asigna permisos según rol",C:"Elimina usuarios",D:"Desactiva logs"}, correcta:"B", explicacion:""},
      {id:20, tema:"Seguridad", enunciado:"Un rootkit es peligroso porque:", opciones:{A:"Mejora rendimiento",B:"Se oculta profundamente en el sistema",C:"Solo afecta redes WiFi",D:"Solo roba cookies"}, correcta:"B", explicacion:""},
      {id:21, tema:"SOR", enunciado:"Promover un servidor implica:", opciones:{A:"Convertirlo en cliente",B:"Instalar AD DS y convertirlo en DC",C:"Activar RAID",D:"Instalar RSAT"}, correcta:"B", explicacion:""},
      {id:22, tema:"SOR", enunciado:"Si el DNS del cliente apunta mal, no podrá:", opciones:{A:"Navegar",B:"Resolver el DC y unirse al dominio",C:"Usar Bluetooth",D:"Usar teclado"}, correcta:"B", explicacion:""},
      {id:23, tema:"SOR", enunciado:"Un RODC es recomendable en:", opciones:{A:"Sede principal",B:"Sede remota con menor seguridad física",C:"Laboratorio doméstico",D:"Router doméstico"}, correcta:"B", explicacion:""},
      {id:24, tema:"SOR", enunciado:"RSAT permite:", opciones:{A:"Gestionar AD desde Windows cliente",B:"Crear RAID",C:"Instalar imágenes PXE",D:"Reemplazar DC"}, correcta:"A", explicacion:""},
      {id:25, tema:"SOR", enunciado:"WDS requiere obligatoriamente:", opciones:{A:"Solo DHCP",B:"AD, DHCP y DNS",C:"Solo DNS",D:"Solo BIOS"}, correcta:"B", explicacion:""},
      {id:26, tema:"SOR", enunciado:"Un RAID5 puede sobrevivir a:", opciones:{A:"Fallo de todos los discos",B:"Fallo de un disco",C:"Fallo de CPU",D:"Fallo de red"}, correcta:"B", explicacion:""},
      {id:27, tema:"SOR", enunciado:"PowerShell remoting se habilita con:", opciones:{A:"Enable-PSRemoting",B:"Start-Domain",C:"Set-RAID",D:"Add-Client"}, correcta:"A", explicacion:""},
      {id:28, tema:"SOR", enunciado:"En LDAP, OU representa:", opciones:{A:"Usuario",B:"Unidad organizativa",C:"Controlador físico",D:"Dominio completo"}, correcta:"B", explicacion:""},
      {id:29, tema:"SOR", enunciado:"Un bosque define:", opciones:{A:"Un único usuario",B:"Conjunto de dominios",C:"Un RAID",D:"Un SIEM"}, correcta:"B", explicacion:""},
      {id:30, tema:"SOR", enunciado:"La replicación AD garantiza:", opciones:{A:"Mismo BIOS",B:"Copia sincronizada entre DCs",C:"Mismo disco",D:"Mismo antivirus"}, correcta:"B", explicacion:""},
      {id:31, tema:"SOR", enunciado:"New-ADUser crea:", opciones:{A:"OU",B:"Grupo",C:"Usuario",D:"Dominio"}, correcta:"C", explicacion:""},
      {id:32, tema:"SOR", enunciado:"La autenticación en dominio es:", opciones:{A:"Distribuida",B:"Centralizada en DC",C:"Manual",D:"Local"}, correcta:"B", explicacion:""},
      {id:33, tema:"SOR", enunciado:"Un dominio representa:", opciones:{A:"Límite de seguridad",B:"Topología física",C:"VLAN",D:"Firewall"}, correcta:"A", explicacion:""},
      {id:34, tema:"SOR", enunciado:"Para administración remota se habilita:", opciones:{A:"Escritorio remoto",B:"RAID",C:"DHCP",D:"Token Ring"}, correcta:"A", explicacion:""},
      {id:35, tema:"SOR", enunciado:"El nivel funcional determina:", opciones:{A:"Capacidad RAM",B:"Funciones disponibles en dominio/bosque",C:"IP",D:"RAID"}, correcta:"B", explicacion:""},
      {id:36, tema:"SOR", enunciado:"ReFS mejora:", opciones:{A:"Seguridad y tolerancia en sistema de archivos",B:"WiFi",C:"DHCP",D:"LDAP"}, correcta:"A", explicacion:""},
      {id:37, tema:"SOR", enunciado:"DHCP en dominio debe:", opciones:{A:"Ser autorizado",B:"Ser manual",C:"Ser externo siempre",D:"Ser opcional"}, correcta:"A", explicacion:""},
      {id:38, tema:"SOR", enunciado:"Instalación remota requiere:", opciones:{A:"PXE habilitado en cliente",B:"USB",C:"ISO local",D:"Bluetooth"}, correcta:"A", explicacion:""},
      {id:39, tema:"SOR", enunciado:"En RAID5, la paridad sirve para:", opciones:{A:"Acelerar red",B:"Reconstruir datos ante fallo",C:"Autenticación",D:"DNS"}, correcta:"B", explicacion:""},
      {id:40, tema:"SOR", enunciado:"La estructura lógica de AD es independiente de:", opciones:{A:"Usuarios",B:"Topología física de red",C:"DNS",D:"GPO"}, correcta:"B", explicacion:""}
    ]
  },
  test3: {
    title: "Test 3 – Examen Final",
    questions: [
      {id:1, tema:"Redes", enunciado:"Un cliente puede hacer ping al DC pero no puede unirse al dominio. El problema más probable es:", opciones:{A:"Fallo de switch",B:"DNS mal configurado",C:"Cable roto",D:"RAID incorrecto"}, correcta:"B", explicacion:""},
      {id:2, tema:"Seguridad", enunciado:"En un ataque MITM, el atacante:", opciones:{A:"Satura el servidor",B:"Se posiciona entre cliente y servidor",C:"Modifica BIOS",D:"Instala RAID"}, correcta:"B", explicacion:""},
      {id:3, tema:"Redes", enunciado:"En el modelo OSI, TCP pertenece a la capa:", opciones:{A:"Red",B:"Transporte",C:"Enlace",D:"Aplicación"}, correcta:"B", explicacion:""},
      {id:4, tema:"Redes", enunciado:"IEEE 802.11 define estándares para:", opciones:{A:"Ethernet cableado",B:"Redes inalámbricas Wi-Fi",C:"Bluetooth clásico",D:"Enrutamiento IPv4"}, correcta:"B", explicacion:""},
      {id:5, tema:"SOR", enunciado:"Un RAID5 mejora la disponibilidad pero penaliza principalmente:", opciones:{A:"Lectura",B:"Escritura",C:"Resolución DNS",D:"Autenticación"}, correcta:"B", explicacion:""},
      {id:6, tema:"Redes", enunciado:"En el modelo OSI, la capa responsable de cifrado y compresión es:", opciones:{A:"Sesión",B:"Presentación",C:"Transporte",D:"Red"}, correcta:"B", explicacion:""},
      {id:7, tema:"Redes", enunciado:"Una red clasificada como WAN se caracteriza por:", opciones:{A:"Alcance doméstico",B:"Alcance metropolitano",C:"Gran escala geográfica",D:"Solo redes inalámbricas"}, correcta:"C", explicacion:""},
      {id:8, tema:"Redes", enunciado:"Si un paquete pierde su ruta correcta, el problema se localiza en la capa:", opciones:{A:"Física",B:"Enlace",C:"Red",D:"Aplicación"}, correcta:"C", explicacion:""},
      {id:9, tema:"Redes", enunciado:"La dirección MAC identifica:", opciones:{A:"Dominio lógico",B:"Dispositivo en la red local",C:"Usuario autenticado",D:"Puerto TCP"}, correcta:"B", explicacion:""},
      {id:10, tema:"Redes", enunciado:"La codificación Manchester garantiza sincronización porque:", opciones:{A:"No hay transiciones",B:"Hay transición en cada bit",C:"Usa doble frecuencia",D:"Usa compresión binaria"}, correcta:"B", explicacion:""},
      {id:11, tema:"Seguridad", enunciado:"Un ataque DDoS compromete principalmente:", opciones:{A:"Confidencialidad",B:"Integridad",C:"Disponibilidad",D:"Autenticación"}, correcta:"C", explicacion:""},
      {id:12, tema:"Seguridad", enunciado:"El phishing es eficaz porque explota:", opciones:{A:"Vulnerabilidades hardware",B:"Confianza y factor humano",C:"Algoritmos de cifrado",D:"RAID mal configurado"}, correcta:"B", explicacion:""},
      {id:13, tema:"Seguridad", enunciado:"Un ataque Zero-Day es peligroso porque:", opciones:{A:"Ya existe parche",B:"No existe parche disponible",C:"Solo afecta IoT",D:"Solo afecta Linux"}, correcta:"B", explicacion:""},
      {id:14, tema:"Seguridad", enunciado:"Un hash criptográfico protege la:", opciones:{A:"Disponibilidad",B:"Integridad",C:"Conectividad",D:"Topología"}, correcta:"B", explicacion:""},
      {id:15, tema:"Seguridad", enunciado:"Un SIEM permite:", opciones:{A:"Crear usuarios",B:"Correlacionar eventos de seguridad",C:"Configurar RAID",D:"Instalar DHCP"}, correcta:"B", explicacion:""},
      {id:16, tema:"Seguridad", enunciado:"Un rootkit es especialmente difícil de detectar porque:", opciones:{A:"Solo actúa en red",B:"Se integra profundamente en el sistema",C:"Solo roba cookies",D:"Se ejecuta en BIOS únicamente"}, correcta:"B", explicacion:""},
      {id:17, tema:"Seguridad", enunciado:"RBAC mejora la seguridad porque:", opciones:{A:"Da acceso completo",B:"Asigna permisos según rol",C:"Elimina autenticación",D:"Sustituye AD"}, correcta:"B", explicacion:""},
      {id:18, tema:"Seguridad", enunciado:"Un keylogger compromete principalmente:", opciones:{A:"Confidencialidad",B:"Disponibilidad",C:"Integridad",D:"RAID"}, correcta:"A", explicacion:""},
      {id:19, tema:"Seguridad", enunciado:"Un ataque MITM puede comprometer:", opciones:{A:"Confidencialidad e integridad",B:"Solo disponibilidad",C:"Solo DNS",D:"Solo MAC"}, correcta:"A", explicacion:""},
      {id:20, tema:"Seguridad", enunciado:"La ingeniería social se basa en:", opciones:{A:"Ataques físicos al cable",B:"Manipulación psicológica",C:"Criptografía avanzada",D:"PXE"}, correcta:"B", explicacion:""},
      {id:21, tema:"SOR", enunciado:"Promover un servidor implica:", opciones:{A:"Convertirlo en cliente",B:"Instalar AD DS y convertirlo en DC",C:"Activar RAID",D:"Instalar RSAT"}, correcta:"B", explicacion:""},
      {id:22, tema:"SOR", enunciado:"Un bosque en Active Directory es:", opciones:{A:"Un único servidor",B:"Conjunto de dominios",C:"Una OU",D:"Un RAID"}, correcta:"B", explicacion:""},
      {id:23, tema:"SOR", enunciado:"Un RODC es recomendable cuando:", opciones:{A:"Se necesita escritura total",B:"La sede tiene menor seguridad física",C:"Es el DC principal",D:"No existe DNS"}, correcta:"B", explicacion:""},
      {id:24, tema:"SOR", enunciado:"Para unir un PC al dominio es imprescindible:", opciones:{A:"Bluetooth",B:"Resolución DNS correcta",C:"ISO local",D:"RAID5"}, correcta:"B", explicacion:""},
      {id:25, tema:"SOR", enunciado:"RSAT permite:", opciones:{A:"Administrar roles de servidor desde cliente Windows",B:"Crear RAID",C:"Reemplazar DC",D:"Instalar BIOS"}, correcta:"A", explicacion:""},
      {id:26, tema:"SOR", enunciado:"WDS se utiliza para:", opciones:{A:"Cifrar datos",B:"Instalación remota vía PXE",C:"Crear grupos",D:"Gestionar RAID"}, correcta:"B", explicacion:""},
      {id:27, tema:"SOR", enunciado:"Enable-PSRemoting permite:", opciones:{A:"Habilitar PowerShell remoto",B:"Crear OU",C:"Crear RAID",D:"Instalar DHCP"}, correcta:"A", explicacion:""},
      {id:28, tema:"SOR", enunciado:"En LDAP, “OU” representa:", opciones:{A:"Usuario",B:"Unidad organizativa",C:"Dominio",D:"Controlador"}, correcta:"B", explicacion:""},
      {id:29, tema:"SOR", enunciado:"La replicación de AD garantiza:", opciones:{A:"Copia sincronizada entre DCs",B:"Igual IP",C:"Igual hardware",D:"Igual BIOS"}, correcta:"A", explicacion:""},
      {id:30, tema:"SOR", enunciado:"El nivel funcional del dominio determina:", opciones:{A:"Tamaño del disco",B:"Funciones disponibles en el dominio",C:"RAM",D:"IP pública"}, correcta:"B", explicacion:""},
      {id:31, tema:"SOR", enunciado:"New-ADGroup crea:", opciones:{A:"OU",B:"Grupo",C:"Usuario",D:"Dominio"}, correcta:"B", explicacion:""},
      {id:32, tema:"SOR", enunciado:"Un dominio representa:", opciones:{A:"Red física",B:"Límite de seguridad lógico",C:"VLAN",D:"Switch"}, correcta:"B", explicacion:""},
      {id:33, tema:"SOR", enunciado:"RAID5 permite tolerancia ante:", opciones:{A:"Fallo de todos los discos",B:"Fallo de un disco",C:"Fallo de CPU",D:"Fallo de red"}, correcta:"B", explicacion:""},
      {id:34, tema:"SOR", enunciado:"ReFS es:", opciones:{A:"Sistema de archivos avanzado",B:"Servicio DHCP",C:"Protocolo red",D:"Herramienta SIEM"}, correcta:"A", explicacion:""},
      {id:35, tema:"SOR", enunciado:"La autenticación en dominio es:", opciones:{A:"Local",B:"Centralizada en DC",C:"Manual",D:"Peer-to-peer"}, correcta:"B", explicacion:""},
      {id:36, tema:"SOR", enunciado:"DHCP en dominio debe estar:", opciones:{A:"Autorizado en AD",B:"Manual",C:"Deshabilitado",D:"Externo obligatorio"}, correcta:"A", explicacion:""},
      {id:37, tema:"SOR", enunciado:"Una OU permite:", opciones:{A:"Delegar administración",B:"Sustituir bosque",C:"Eliminar dominio",D:"Cambiar BIOS"}, correcta:"A", explicacion:""},
      {id:38, tema:"SOR", enunciado:"La instalación remota requiere que el cliente soporte:", opciones:{A:"PXE",B:"RAID",C:"SIEM",D:"Bluetooth"}, correcta:"A", explicacion:""},
      {id:39, tema:"SOR", enunciado:"PowerShell facilita la administración porque permite:", opciones:{A:"Automatización mediante scripts",B:"Sustituir AD",C:"Evitar DNS",D:"Desactivar firewall"}, correcta:"A", explicacion:""},
      {id:40, tema:"SOR", enunciado:"Active Directory separa:", opciones:{A:"Estructura lógica y física",B:"RAID y ReFS",C:"DHCP y DNS",D:"MAC y IP"}, correcta:"A", explicacion:""}
    ]
  }
};
